### ISSUE TITLE
Doesn't build with JDK7 on Windows

### ISSUE THREAD

**Issue by fmoule** [UISpec4J/UISpec4J#11]
Hi everybody

When i try to compile the project with the JDK7 parameters, i get the following test failure :

testSetInputFollowedByACancelInJOptionPaneReturnsTheInputValue(org.uispec4j.interception.BasicHandlerTest): Component 'Cancel' of type 'button' not found - available names: [Annuler,OK].

I guess it's a "i18n" problem ;)

Frédéric

**Comment by nebulorum** [comment]
Yes this is a i18n problem. You have to use localized name when finding buttons.
