### ISSUE TITLE
Recover and document the release process

### ISSUE THREAD

**Issue by nebulorum** [UISpec4J/UISpec4J#13]
I really think we should release at new versions. Could be 2.4.1 or 2.5. I'm happy to do this, but I don't know the following:
- How to update the site
- Where to release the artifact to
- How to release
- Credentials to all of the places.

Thomas

**Comment by falkoschumann** [comment]
Is a release planned in near future?

**Comment by nebulorum** [comment]
2.5-RC1 is up on maven central. I'm waiting for some feedback. But might as well release 2.5.

**Comment by falkoschumann** [comment]
I try 2.5-RC1 from maven central. The first try doesn't work, I change only the dependency version from 2.4 to 2.5-RC1. The assert "No window was shown (timeout expired)" failed.

In the second try I add classifier jdk8 to UISpec4J dependency. This works. Must I add the classifier depend on the JDK I use?

**Comment by optimix** [comment]
Indeed:
```java
import org.junit.Before;
import org.junit.Test;
import org.uispec4j.Trigger;
import org.uispec4j.UISpec4J;
import org.uispec4j.interception.WindowInterceptor;

import javax.swing.*;

public class MyTest {

	@Before
	public void setUp() throws Exception {
		UISpec4J.init();
	}

	@Test
	public void testMe() throws Exception {
		WindowInterceptor
				.run(new Trigger() {
					public void run() throws Exception {
						final JFrame jFrame = new JFrame();
						jFrame.setVisible(true);
					}
				});
	}
}
```

And output:
```java
java.lang.AssertionError: No window was shown (timeout expired)
	at org.junit.Assert.fail(Assert.java:88)
	at org.uispec4j.assertion.testlibrairies.JUnitLibrary.fail(JUnitLibrary.java:7)
	at org.uispec4j.assertion.testlibrairies.AssertAdapter.fail(AssertAdapter.java:11)
	at org.uispec4j.interception.handlers.ShownInterceptionDetectionHandler.waitWindow(ShownInterceptionDetectionHandler.java:39)
	at org.uispec4j.interception.WindowInterceptor.run(WindowInterceptor.java:324)
	at org.uispec4j.interception.WindowInterceptor.run(WindowInterceptor.java:290)
	at MyTest.testMe(MyTest.java:18)
...
```

In my fork, I had also modified the Empty class to make setVisible(true) act like show():
https://github.com/optimix/UISpec4J/commit/6760e3ff815c64482fd0360fc1eec9243cbb2a66#diff-57a8285f2c664ad2198b5600f214706e

**Comment by nebulorum** [comment]
Yes you need the classifiers. In principal openjdk7 should work since that is what I use on CI. I'm stopping some threading issues on the CI, will fold them into the main branch. But it's all in the tests not the UISpec4J code.

**Comment by optimix** [comment]
Oh yes, I forgot the classifier. Adding the classifier jdk7 solves the "No window was shown" error.

**Comment by optimix** [comment]
I works fine. There is only one detail when running it on Debian.

The XToolkit class does a initXSettingsIfNeeded() when we call addPropertyChangeListener() which calls loadXSettings() and instanciates XAWTXSettings.
However, when instanciating XAWTXSettings, initXSettings() is called and then initPerScreenXSettings() which considers that Toolkit.getDefaultToolkit() returns an XToolkit.

http://hg.openjdk.java.net/jdk7/jdk7/jdk/file/3b9a288d7ddb/src/solaris/classes/sun/awt/X11/XToolkit.java
http://hg.openjdk.java.net/jdk7/jdk7/jdk/file/3b9a288d7ddb/src/solaris/classes/sun/awt/X11/XAWTXSettings.java

I had to add the following hack right after calling UISpec4J.init() so that we initialize what we need on the underlying toolkit before using the toolkit.
```java

			UISpecToolkit uiSpecToolkit = (UISpecToolkit) Toolkit.getDefaultToolkit();
			Toolkit underlyingToolkit = uiSpecToolkit.getUnderlyingToolkit();

			Field e = Toolkit.class.getDeclaredField("toolkit");
			e.setAccessible(true);
			e.set(null, underlyingToolkit);

			PropertyChangeListener dummyListener = new PropertyChangeListener() {
				public void propertyChange(PropertyChangeEvent evt) {
				}
			};
			underlyingToolkit.addPropertyChangeListener(SunToolkit.DESKTOPFONTHINTS, dummyListener);
			underlyingToolkit.removePropertyChangeListener(SunToolkit.DESKTOPFONTHINTS, dummyListener);

			e.set(null, uiSpecToolkit);
```

**Comment by nebulorum** [comment]
Closing, if still relevant please reopen.
