### ISSUE TITLE
Troubles compiling it in JDK8u31

### ISSUE THREAD

**Issue by lqbweb** [UISpec4J/UISpec4J#14]
UiSpecToolkit that inherites ToolkitDelegate is not compiling, since it is missing to implement a method. Just adding the empty method works, but not sure that this means.

Also, I have some tests failing.

And I can't compile some of the samples.

**Comment by nebulorum** [comment]
Can you be a bit more specific? 

UISpec4J has different build profiles for each version of the SDK. This may cause the problem.

Some test are failing on Linux because the toolkit actually casts itself to the real class. If not on Linux can you please provide more information?

**Comment by lqbweb** [comment]
Yes sure,

I found that ToolkitDelegate in the JDK8 profile does not implement:

public DataTransferer getDataTransferer();

which was added to JDK8 here:

http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/rev/1952706b45c0


If you need any more help, please let me know.

Regards,
Ruben

**Comment by nebulorum** [comment]
I just checked on my u5 and it works. With u31 it doesn't. The other issue is that a lot of this is internal APIs. I'd suggest using one of the built version for the mean time while I fix this.

**Comment by nebulorum** [comment]
I adde the missing method. Worked on my Mac. I'll be trying to get Travis setup so we have more platform coverage.

**Comment by nebulorum** [comment]
Thanks for the input. I fixed this issue and also added the needed data to build it on Travis.

There were two problems:
1)  The method added on updated 31
2) The examples were broken for JDK8 and actually all JDK.

Both are now fixed and you can see this on Travis: https://travis-ci.org/UISpec4J/UISpec4J
