### ISSUE TITLE
Tests fail on Linux with JDK 8

### ISSUE THREAD

**Issue by pdhammond42** [UISpec4J/UISpec4J#19]
Building with Oracle JDK 1.8.0_20 fails with a test error. The key piece of stack trace is 

    Caused by: java.lang.ClassCastException: org.uispec4j.interception.toolkit.UISpecToolkit cannot be cast to sun.awt.X11.XToolkit
    	at sun.awt.X11.XAWTXSettings.initPerScreenXSettings(XAWTXSettings.java:111)
	at sun.awt.X11.XAWTXSettings.initXSettings(XAWTXSettings.java:63)
	at sun.awt.X11.XAWTXSettings.<init>(XAWTXSettings.java:53)
	at sun.awt.X11.XToolkit.loadXSettings(XToolkit.java:1553)
	at sun.awt.X11.XToolkit.initXSettingsIfNeeded(XToolkit.java:1524)
	at sun.awt.X11.XToolkit.addPropertyChangeListener(XToolkit.java:1506)
	at org.uispec4j.interception.toolkit.ToolkitDelegate.addPropertyChangeListener(ToolkitDelegate.java:285)

Looking at the OpenJDK source shows it is trying to cast the default toolkit to XToolkit
http://www.docjar.com/docs/api/sun/awt/X11/XAWTXSettings.html

        // we must not  invoke this under Awt Lock
        ((XToolkit)Toolkit.getDefaultToolkit()).parseXSettings(0,updatedSettings);

No idea how/if this ever worked, and more importantly no idea how I might fix it. Sorry but Java's not my best language.

**Comment by nebulorum** [comment]
This is going to be really hard to solve. The UISpecToolkit does not extend that Toolkit and I don't think we can cast it. The solution to this will be using dynamic proxy, which is something I want to do, but not at the current release cycle.

This worked on older SDK because it used the MToolkit on Linux, but that was removed on JDK7. 

Is this impacting too many tests?

**Comment by pdhammond42** [comment]
I'm not sure how many UISpec4j tests it is affecting, or if that was what you meant. It's affecting all of my tests, because it happens in initialisation; red all across the board. May have to drop back to JDK 6.

**Comment by nebulorum** [comment]
I double checked on my build server. JDK6 will work on Linux. For JDK7 or JDK8 you can use another Toolkit like the one in  `ci-headless` profile of the current project (https://github.com/UISpec4J/UISpec4J/blob/master/uispec4j/pom.xml). I use this on Travis-CI.

In essence you include another dependency and add the following to the build. This allows you to run your test without using the Linux Toolkit. This Gist has what you need:
https://gist.github.com/nebulorum/ff98817c9aec4f032911

Cacio-TTA does pass all the UISpec4J tests. I'm still getting some issues with Modal Dialogs, but I think those are mostly related to threading and race conditions on dispatcher loops.

**Comment by pdhammond42** [comment]
Yes, that has fixed it. My tests are now all green. (Which is good because I looked at dynamic proxies and couldn't get anywhere due to the toolkit being a final concrete class.) 

Many thanks.

**Comment by nebulorum** [comment]
I did some investigating and both XToolkit and the Mac LWCToolkit are final. There are way around this, but it will be really annoying to get this fixed.

**Comment by pdhammond42** [comment]
I suppose this issue can be closed then. Do you do that or do I?
Thanks again..

**Comment by nebulorum** [comment]
This will be a target for 2.6. But lets close it for now.
