### ISSUE TITLE
Writing extension for custom components

### ISSUE THREAD

**Issue by kameshakr** [UISpec4J/UISpec4J#27]
I was looking for documentation on how to write custom adapter for custom components and finding it hard as uispec4j.org site is down. Any chance you can provide me the details of how we write adapters for custom components

Many Thanks!!!

**Comment by nebulorum** [comment]
I'm still working of recovering the site. As far as I remember there are two ways to look at this:

1.  Your component is built of several other components. 
2.  Your have a component for scratch

In the first case I'd test the component in isolation, using standard UISpec4J. What you want to make sure is that you test the logic. I've done this several times.

The second case requires extending UISpec4J. There is a generator that will allow you to create a class to add hooks to your component. This can allow you to have test for things like actions on your components. In order for this to work, your extensions have to be added before UISpec4J on the classpath. 

In my experience every time I thought of testing via extension, I ended up reverting to the first strategy. But it really depends on what you need.

**Comment by nebulorum** [comment]
Some of the old documentation is back on line:

http://uispec4j.github.io/UISpec4J/legacy-doc/generated/extension.html

Not very much there but it does link the Javadoc

**Comment by nebulorum** [comment]
Closing, if still relevant please reopen.
