### ISSUE TITLE
How do we handle a modal dialog which may or may not be shown?

### ISSUE THREAD

**Issue by kameshakr** [UISpec4J/UISpec4J#28]
I am trying to handle this scenario and don't see it obvious

I am entering log in details and pressing Login button
Upon clicking that if successful a splash screen is shown and it is followed by main window (I was able to check this)

But if the user credentials are wrong/if user is already logged in/if server is down an Error dialog will appear. 
How do we handle this?
I tried to handle it in couple of ways and both seems to be failing with No window was shown (timeout expired) error in both cases?

Can the above use case be supported at all or am I missing something very trivial?

**Comment by nebulorum** [comment]
Closing, if still relevant please reopen.
