### ISSUE TITLE
PopupMenuInterceptor for lists not working because of wrong height computation

### ISSUE THREAD

**Issue by christophpickl** [UISpec4J/UISpec4J#30]
i am using uispec4j 2.5-RC1 and want to do something like this: `PopupMenuInterceptor.run(list.triggerRightClick(0))`

this will result in a timeout, as the dispatched MouseEvent has a wrong y-coordinate. by debugging, i figured out the list cell height is computed to -1 by `BasicListUI#getHeight`. i've tried a hack by setting the fixedCellHeight which will be taken into account by `maybeUpdateLayoutState` which calls `updateLayoutState`. and there is the thing: `UISpecListUI` overrides `maybeUpdateLayoutState` with an empty implementation, so recalculation of cell heights is suppressed and the cellHeight variable stays at -1 and the `ListBox#rightClick` method will get back a wrong Rectangle instance with a height set to -1, which of course leads to no popup being displayed.

i hope i could summarize this issue in a proper way as the problem is somehow not that trivial. if it is obvious what to do, i am willing to fix this issue on my own, but i am afraid simply NOT overriding the `maybeUpdateLayoutState` doesn't solve the bug as there has been most likely a reason to do that.

[UPDATE]
i've created a sample project https://github.com/christophpickl/uispec4j_listbug/ which demonstrates that the bug is related to the `getCellBounds()` computation. everything works just fine when using the conventional `locationToIndex()` method, but when switching to manually computing the index (in a more precise way) with the help of cell bounds, UISpec4J returns wrong Rectangle instances (see inline comments in sample code).

this might also affect other UI components than JList, but i had no time yet to test this.

TIA,
christoph

**Comment by nebulorum** [comment]
I suspect that position are not really usable. UIspe4J does not really generate the full of UI as far as I know. So you may be looking at a window that was not resized. This means that geometry calculation would fail.

Can you work without the position component?

**Comment by christophpickl** [comment]
hi, first of all thanks for the reply. the answer is: yes-no ;) i can use the standard locationToIndex() method to calculate the row index for a given point, which i do not prefer as this also includes clicks below the last entry, as this is the default behaviour. so what, i can live with that...
but now another issue just popped up, which i need to investigate further, concerning ListBox#rightClick which internally leads to a getCellBounds() method invocation, which is the method which causes my troubles, but this time i cant just change my requirements because of UISpec4J specifics... workaround: skip the test ;)

**Comment by nebulorum** [comment]
Closing, if still relevant please reopen.
