### ISSUE TITLE
Object SPY - get GUI fields object properties of Swing app

### ISSUE THREAD

**Issue by SanjeevKumarmn** [UISpec4J/UISpec4J#32]
Is there any open source tool available to spy any Java Swing apps in order to get GUI fields object properties?

**Comment by johnstosh** [comment]
Hi Masval,

Do you mean to spy some Swing components you're doing a JUnit test upon, or
do you mean to spy on a JVM running Swing from outside of that process?
For the second case, you can do what the NetBeans IDE does -- it uses the
debugging interface which is used to attach to an external JVM and set
breakpoints, examine objects, etc.

Kind Regards,
Johnny

--
Johnny Muczynski
734-262-2045

**Comment by SanjeevKumarmn** [comment]
Thanks Johnny for responding. I mean spying the Java swing app similar to UISPy.exe or inspect.exe that windows provides the field properties like ID or Name.

**Comment by nebulorum** [comment]
Still an issue? If so reopen.
