### ISSUE TITLE
ui4j WebKit Browser.navigate is hanging linux

### ISSUE THREAD

**Issue by subhasispatra** [UISpec4J/UISpec4J#33]
I am using ui4j-all-2.1.0.jar for my project. While navigating to URL, the application freezes yielding a stuck thread issue. Same is working in windows. 

Thread [AJAX: executeSelectedTestSuite - 48844::JUNIT_TestImageGeneration - 48845: 28]
	sun.misc.Unsafe.park(Native Method)
	java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	com.sun.javafx.application.PlatformImpl.waitForStart(PlatformImpl.java:256)
	com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:277)
	com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:268)
	javafx.application.Platform.runLater(Platform.java:83)
	com.ui4j.webkit.WebKitBrowser.navigate(WebKitBrowser.java:382)
	com.ui4j.webkit.WebKitBrowser.navigate(WebKitBrowser.java:341)

**Comment by nebulorum** [comment]
Closing, if still relevant please reopen.
