### ISSUE TITLE
Build error with JDK 7and 8 - Adopt OpenJDK feedback 

### ISSUE THREAD

**Issue by ghost** [UISpec4J/UISpec4J#5]
Hi all,

JBehave is using UISpec4j:
http://jira.codehaus.org/browse/JBEHAVE-932

But  mvn test from uispec4j is broken with java 7 and 8

java version "1.7.0_25"
Java(TM) SE Runtime Environment (build 1.7.0_25-b15)
Java HotSpot(TM) Server VM (build 23.25-b01, mixed mode)

[INFO] Compiling 157 source files to /home/hf/Desktop/cejug/adopt_openjdk/UISpec4J/uispec4j/target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING]  package org.uispec4j.interception.toolkit

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] bootstrap class path not set in conjunction with -source 1.5

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.304s
[INFO] Finished at: Sun Jul 14 10:52:50 BRT 2013
[INFO] Final Memory: 12M/126M
[INFO] ------------------------------------------------------------------------

**Comment by gangji91** [comment]
Hi @nebulorum 

We have been using this UISpec4J version 2.3 in our tests in Java 6.

We have recently upgraded to Java 7, upgrade 37, and our tests therefore no longer work. We would be happy to upgrade to UISpec4J version 2.5, but our company QA policy does not allow us to use a snapshot version, only a released version.

I just wanted to enquire if you have any plans to release version 2.5?
Thanks in advance.

**Comment by nebulorum** [comment]
Closing, if still relevant please reopen.
